### ISSUE TITLE
Peer Review 12/11

### ISSUE THREAD

**Issue by didiercatz** [StanBankras/frontend-data#1]
### Research questions

- Are parkingspots closer to public transport to continue your travel this way?
_I can't really seem to read this off the graph. Is this implemented yet? Right now, I only see percentages._

- Do parkingspots generally have more charging points for electrical cars?
_Nice! I can read this off the table perfectly._
- Are parkingspot in environment zones with more charging points more expensive to park?
_Nice! I can read this off the table perfectly._

### Application of subject matter
You have a working, interactive visualisation. Of course there's still some polishing left to do as you've mentioned, but all in all it sells the concept well. You use Git correctly and your knowledge of D3 is visible.

### Understanding
- I'm pretty sure you understand most of your code, but I would like to see some more code comments, especially on your utility/helper functions, since they get quite complex.

- Awesome work with the store.
- I would recommend stepping away from string concatenation in favour of template literals (for example, in https://github.com/StanBankras/frontend-data/blob/main/src/utils/helpers.js#L18-L26). This way, your code becomes a lot more human-readable.
```js
const name = lastName + ', ' + firstName 

// becomes

const name = `${lastName}, ${firstName}` 
```

### Quality
Code quality is very good. Take the previously mentioned points into consideration and you've got yourself a great project. I do think using tools like ESLint or Prettier would help with consistency as I see some slight variation here and there.

### Process
Your wiki looks great all in all. Choices are evaluated and documented; progress is demonstrated; Work reflects client's needs.

**Comment by StanBankras** [comment]
Thanks for the review and valid points @didiercatz.
I will take all of these points into account -- broke it down into multiple issues.
